services:
  database:
    image: postgres:alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django_uploader:
    build:
      context: ./upload_files_project/.
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./upload_files_project:/usr/src/app/
    depends_on:
      - database
    environment:
      - SECRET_KEY=django-insecure-5=3(85+osx4ig4%^!h4bgqq6^o1i_c%h4)a8o80#)yk2q9cuxa
      - ALLOWED_HOSTS=127.0.0.1
      - DEBUG=1
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres


  redis:
    image: redis:alpine3.18
    hostname: redis

  worker:
    build:
      context: ./upload_files_project/.
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./upload_files_project:/usr/src/app/
    environment:
      - SECRET_KEY=django-insecure-5=3(85+osx4ig4%^!h4bgqq6^o1i_c%h4)a8o80#)yk2q9cuxa
      - ALLOWED_HOSTS=127.0.0.1
      - DEBUG=1
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    links:
      - redis
    depends_on:
      - redis
      - database

  flower:
    build:
      context: ./upload_files_project/.
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./upload_files_project:/usr/src/app/ 
    environment:
      - SECRET_KEY=django-insecure-5=3(85+osx4ig4%^!h4bgqq6^o1i_c%h4)a8o80#)yk2q9cuxa
      - ALLOWED_HOSTS=127.0.0.1
      - DEBUG=1
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
    